schema:
    - ./graphql/schema.graphql
    - ./graphql/client-schema.graphql
documents:
    - ./graphql/**/*.gql
extensions:
    codegen:
        generates:
            ./graphql/__generated__/:
                preset: client
                config:
                    unmaskFunctionName: unmask
        plugins:
            - client-preset
            - typescript
            - typescript-operations
            - typescript-react-apollo
        config:
            - preResolveTypes: true
            - nonOptionalTypenames: true
        presetConfig:
            gqlTagName: gql
            unmaskFunctionName: unmask
        ignoreNoDocuments: true
        verbose: true
overwrite: true
